# config.yaml file

# data retrieval
refresh: 150
interval: 5m

enable_sound: True

# strategy
strategy: wma
strategy_params:
  - 34
  - 34

# email notification
email_prefix: Test_01
email_receivers:
  # - youremail1@gmail.com
  # - youremail2@gmail.com
# add to the email subject to distinguish different config (if you want to test multiple strategy or parameters)
email_mode: notification # notification or reminder

# real time simulation/trade
init_balance: 1000

# robinhood
enable_robinhood: False # True or False

#logs
status_file: 'logs/status.json'
history_file: 'logs/history.csv'
log_file: 'logs/log.log'

# watch list
watch_list:
  - SPY
  - AAPL
  - MSFT
  - AMD
  - INTC
  - GOOGL


  # ticker strategy
ticker_strategy:
  INTC: [supertrend, 5, 377]
  GOOGL: [rvwma, 55, 145]
