# config.yaml file

# data retrival
refresh: 150
interval: 5m

# strategy
strategy: wma
strategy_params:
  - 34
  - 34

# email notification
email_receivers:
  # - youremail1@gmail.com
  # - youremail2@gmail.com
# add to the email subject to dinstinghish different config (if you want to test multiple strategy or parameters)
email_prefix: Test_01

# real time simulation/trade
init_balance: 1000

# robinhood
enable_robinhood: false # true or false

#logs
status_file: "logs/status.json"
history_file: "logs/history.txt"
log_file: "logs/log.log"

# watch list
Watchlist:
  - TQQQ
  - FNGU
  - SPY
  - QYLD
  - ARKW
  - WCLD
  - NIO
  - SHLL
  - AAPL
  - MSFT
  - AMD
  - INTC
  - ZM