# config.yaml file

# data retrieval
refresh: 150
interval: 5m

# strategy
strategy: wma
strategy_params:
  - 34
  - 34

# email notification
email_prefix: Test_01
email_receivers:
  # - youremail1@gmail.com
  # - youremail2@gmail.com
# add to the email subject to distinguish different config (if you want to test multiple strategy or parameters)
email_mode: notification # notification or reminder

# real time simulation/trade
init_balance: 1000

# robinhood
enable_robinhood: false # true or false

#logs
status_file: 'logs/status.json'
history_file: 'logs/history.txt'
log_file: 'logs/log.log'

# watch list
watch_list:
  - SPY
  - AAPL
  - MSFT
  - AMD
  - INTC
